.PHONY: all
all:
	make TARGET=01_hello_world.sh -f ../Makefile_sh
	make TARGET=03_bash_variables.sh -f ../Makefile_sh
	make TARGET=05_bash_env_variables.sh -f ../Makefile_sh
	make TARGET=06_bash_declare.sh -f ../Makefile_sh
	make TARGET=07_bash_special_parameters.sh -f ../Makefile_sh
	make TARGET=08_bash_if.sh -f ../Makefile_sh
	make TARGET=08_bash_for.sh -f ../Makefile_sh
	make TARGET=08_bash_while.sh -f ../Makefile_sh
	make TARGET=08_bash_until.sh -f ../Makefile_sh
	make TARGET=08_bash_case.sh -f ../Makefile_sh
	make TARGET=09_bash_function.sh -f ../Makefile_sh
