.PHONY: all
all:
	make TARGET=01_declare_integer.sh -f ../Makefile_sh
	make TARGET=02_declare_array.sh -f ../Makefile_sh
	make TARGET=03_declare_map.sh -f ../Makefile_sh
	make TARGET=06_conditional_constructs1.sh -f ../Makefile_sh
	make TARGET=06_conditional_constructs2.sh -f ../Makefile_sh
	make TARGET=06_conditional_constructs3.sh -f ../Makefile_sh
	make TARGET=06_conditional_constructs_pattern_matches.sh -f ../Makefile_sh
	make TARGET=06_conditional_constructs_regex.sh -f ../Makefile_sh
